# Generates seed media for the network-smoke docker containers.
# Run from the repo root: pwsh tools/network-smoke/make-seed.ps1
$ErrorActionPreference = "Stop"

$seedDir = Join-Path $PSScriptRoot "seed"
New-Item -ItemType Directory -Force -Path $seedDir | Out-Null

# Text file (remote text preview + edit smoke).
@"
X-Files network smoke — FTP/SFTP seed
Generated by tools/network-smoke/make-seed.ps1
"@ | Set-Content -Path (Join-Path $seedDir "seed.txt") -Encoding utf8

# Tiny PNG (remote image preview smoke) — copy one from the repo docs.
$png = Get-ChildItem -Path (Join-Path $PSScriptRoot "..\..\docs\icons") -Filter "*.png" -File | Select-Object -First 1
if ($png) {
    Copy-Item -LiteralPath $png.FullName -Destination (Join-Path $seedDir "seed.png") -Force
}

# Short WAV (remote audio playback smoke) — synthesized 440Hz sine, ~3s.
$out = Join-Path $seedDir "seed.wav"
$sampleRate = 44100
$seconds = 3
$n = $sampleRate * $seconds
$bytes = New-Object byte[] (44 + $n * 2)

function Copy-Bytes([byte[]]$src, [byte[]]$dst, [int]$offset) {
    [Array]::Copy($src, 0, $dst, $offset, $src.Length)
}

# RIFF header
Copy-Bytes ([Text.Encoding]::ASCII.GetBytes("RIFF")) $bytes 0
Copy-Bytes ([BitConverter]::GetBytes([int](36 + $n * 2))) $bytes 4
Copy-Bytes ([Text.Encoding]::ASCII.GetBytes("WAVE")) $bytes 8
Copy-Bytes ([Text.Encoding]::ASCII.GetBytes("fmt ")) $bytes 12
Copy-Bytes ([BitConverter]::GetBytes([int]16)) $bytes 16
Copy-Bytes ([BitConverter]::GetBytes([int16]1)) $bytes 20
Copy-Bytes ([BitConverter]::GetBytes([int16]1)) $bytes 22
Copy-Bytes ([BitConverter]::GetBytes([int]$sampleRate)) $bytes 24
Copy-Bytes ([BitConverter]::GetBytes([int]($sampleRate * 2))) $bytes 28
Copy-Bytes ([BitConverter]::GetBytes([int16]2)) $bytes 32
Copy-Bytes ([BitConverter]::GetBytes([int16]16)) $bytes 34
Copy-Bytes ([Text.Encoding]::ASCII.GetBytes("data")) $bytes 36
Copy-Bytes ([BitConverter]::GetBytes([int]($n * 2))) $bytes 40

for ($i = 0; $i -lt $n; $i++) {
    $v = [int16]([math]::Sin(2.0 * [math]::PI * 440.0 * $i / $sampleRate) * 12000.0)
    $b = [BitConverter]::GetBytes($v)
    $bytes[44 + $i * 2] = $b[0]
    $bytes[44 + $i * 2 + 1] = $b[1]
}
[IO.File]::WriteAllBytes($out, $bytes)

Write-Host "Seed written to $seedDir"
Get-ChildItem $seedDir | Select-Object Name, Length
