# generate-devportal-secrets.ps1
# Reads .env (repo root) and writes XFiles/DevPortalSecrets.g.cs with the Dev Portal
# credentials. .env is gitignored, so real credentials never enter the repo or the
# generated file is empty when .env is missing.
# Called as PreBuildEvent by MSBuild (after increment-version.ps1).

$ErrorActionPreference = 'Stop'

$solutionDir = $env:SolutionDir
if (-not $solutionDir -or -not (Test-Path $solutionDir)) {
    $solutionDir = Split-Path -Parent $PSScriptRoot
}
if (-not $solutionDir -or -not (Test-Path $solutionDir)) {
    Write-Error "Cannot determine solution directory. Set SolutionDir environment variable."
    exit 1
}

$envPath   = Join-Path $solutionDir '.env'
$outPath   = Join-Path $solutionDir 'XFiles\DevPortalSecrets.g.cs'

$user = ''
$pass = ''

if (Test-Path $envPath) {
    Get-Content $envPath | ForEach-Object {
        $line = $_.Trim()
        if ($line -and -not $line.StartsWith('#')) {
            $kv = $line -split '=', 2
            if ($kv.Count -eq 2) {
                $key = $kv[0].Trim()
                $val = $kv[1].Trim()
                if ($key -eq 'DEV_PORTAL_USER') { $user = $val }
                elseif ($key -eq 'DEV_PORTAL_PASS') { $pass = $val }
            }
        }
    }
}

if (-not $user -and -not $pass) {
    Write-Host '[devportal] .env missing or empty — generated DevPortalSecrets.g.cs with NO credentials'
}

$escapedUser = $user.Replace('\', '\\').Replace('"', '\"')
$escapedPass = $pass.Replace('\', '\\').Replace('"', '\"')

$content = @"
// <auto-generated>
// Generated by tools/generate-devportal-secrets.ps1 from .env (gitignored).
// DO NOT EDIT — manual edits are overwritten on every build.
// </auto-generated>
namespace XFiles.Services
{
    internal static class DevPortalSecrets
    {
        public static readonly string User = "$escapedUser";
        public static readonly string Password = "$escapedPass";
    }
}
"@

Set-Content -Path $outPath -Value $content -NoNewline -Encoding UTF8
Write-Host "[devportal] wrote DevPortalSecrets.g.cs"
